### ISSUE TITLE
Readme note about AUR

### ISSUE THREAD

**Issue by C0rn3j** [Ashark/davinci-resolve-checker#13]
https://aur.archlinux.org/packages/python-pylspci/
pylspci is now in AUR and thus doesn't need to be installed through pip

**Comment by Ashark** [comment]
Thanks

**Comment by C0rn3j** [comment]
You can't install AUR packagers straight through pacman, I suggest you just note the package and link to https://wiki.archlinux.org/index.php/Arch_User_Repository

**Comment by Ashark** [comment]
Oh, thanks again! I will example with yay, as it is common aur helper.

**Comment by C0rn3j** [comment]
I'd suggest against doing that as package managers come and go, but linking to the AUR page is permanent, but up to you, thanks for fixing it either way.
