### ISSUE TITLE
Script wrongly says I don't use Pro OpenGL 

### ISSUE THREAD

**Issue by pacifi5t** [Ashark/davinci-resolve-checker#14]
![Screenshot_20210213_164532](https://user-images.githubusercontent.com/57317100/107853166-1b88f700-6e1d-11eb-8f74-00a2d3e5269d.png)

DaVinci works just fine with this `progl` command

**Comment by Ashark** [comment]
Спасибо, поправил.
А как ты запускал DR? У меня тоже  RX580, тоже поставил opencl-amd-polaris, но DR не запускается.
```
$ progl davinci-resolve-checker.py 
DaVinci Resolve checker 1.4.2
Installed DaVinci Resolve package: davinci-resolve 16.2.8-1

Chassis type: desktop
Installed OpenCL drivers: opencl-amd-polaris
Presented GPUs:
        Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (kernel driver in use: amdgpu)
OpenGL vendor string: Advanced Micro Devices, Inc.

All seems good. You should be able to run DaVinci Resolve successfully.
```

**Comment by pacifi5t** [comment]
Привет. Я смотрю у тебя DR 16-ой версии. У меня его никак не получилось запустить, поэтому я использую версию 17 beta. Она работает без проблем, если в команду запуска дописать в начале progl.

Из пакетов, которые я ставил чтобы оно заработало:
xf86-video-amdgpu
libva-mesa-driver
opencl-amd-polaris
amdgpu-pro-libgl
vulkan-radeon //Не уверен, что он тут нужен, но кто-то рекомендовал
P.S. Если получится запустить, то возможно отсутствие звука во время предпросмотра видео, решение: https://www.youtube.com/watch?v=9K9b2tXLGrw (https://link.getmailspring.com/link/05770775-D6C4-4CE6-A031-332D09413E9F@getmailspring.com/0?redirect=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D9K9b2tXLGrw&recipient=cmVwbHkrQU5WSk4zR1UyUFRCRlhKUEZHNUpDNU42R1FDSUZFVkJOSEhEQUpNREFVQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by Ashark** [comment]
Спасибо за ответ, да, как ни странно, 17-я версия заработала.
Спасибо за совет с аудио и за поправку на Вики. Но я с такой проблемой не сталкивался.
