### ISSUE TITLE
Consider using `dmidecode` instead of `hostnamectl` as the first one is not dependent on Systemd

### ISSUE THREAD

**Issue by AryToNeX** [Ashark/davinci-resolve-checker#16]
`hostnamectl status` can be replaced by `dmidecode --type 3` run as root. While the latter approach is privileged, it is actually compatible with non-Systemd distros such as Artix Linux.

The regex that understands the chassis type would then have to be reworked from `Chassis: ` to `Type: `.

**Comment by Ashark** [comment]
I actually run the dr checker by my launch script every dr run. So I dislike the idea of running the privileged command.
Don't you know another way to check it on a non-systemd distros?

**Comment by AryToNeX** [comment]
> I actually run the dr checker by my launch script every dr run. So I dislike the idea of running the privileged command.
> Don't you know another way to check it on a non-systemd distros?

I've tried to search for userspace alternatives and I didn't really find a thing :C

**Comment by Ashark** [comment]
I have found solutions relied on battery presence (unreliable) or presence of [lid](https://stackoverflow.com/a/68676700/7869636) (probably better).
But I also have remembered, that you can query chassis info without sudo by reading /sys/class/dmi/id/chassis_type (see https://superuser.com/a/1107191/873855).
