### ISSUE TITLE
Unsupported chassis - Convertible

### ISSUE THREAD

**Issue by slch** [Ashark/davinci-resolve-checker#30]
`Warning: you chassis type is not supported by the script. Please report your case.`

Reporting.

<details>
<summary>Full output</summary>

```
d/git/davinci-resolve-checker ./davinci-resolve-checker.py
Locale unavailable: None, using en_US instead
Using locale en_US
DaVinci Resolve checker 2.6.2
Installed DaVinci Resolve package: 
Chassis type: Convertible
Warning: you chassis type is not supported by the script. Please report your case.
```
</details>

Laptop is `Lenovo YOGA 530` (also called `Lenovo Flex 14` in USA).

Adding `Convertible` to [`supported_chassis_types`](https://github.com/Ashark/davinci-resolve-checker/blob/2880b81f0c745e3de078266b4952e76568ebbc92/davinci-resolve-checker.py#L91) worked and produced the following output:
(which should be correct as i only have 1 integrated gpu)

<details>
<summary>New output</summary>

```
d/git/davinci-resolve-checker ./davinci-resolve-checker.py
Locale unavailable: None, using en_US instead
Using locale en_US
DaVinci Resolve checker 2.6.2
Installed DaVinci Resolve package: 
Chassis type: Convertible
Installed OpenCL drivers: 
Presented GPUs:
        UHD Graphics 620 (kernel driver in use: i915)
OpenGL vendor string: Intel

You have only Intel GPU. Currently DR cannot use intel GPUs for OpenCL. You cannot run DR. See https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=81579
```

</details>

**Comment by Ashark** [comment]
@RannyBergamotte Are you saying that you got DR working on intel only?
