### ISSUE TITLE
This script says that I cannot run Davinci Resolve, but I can run it successfully

### ISSUE THREAD

**Issue by senge-studio** [Ashark/davinci-resolve-checker#31]
My Laptop is Xiaomi Notebook Pro with Intel Iris Xe graphic card, (I have no nvidia card(s).)
My Linux distro is Arch Linux
This script says that I cannot run Davinci Resolve, however, I can run Davinci Resolve successfully. 
Btw, I installed davinci resolve by aur.

This is the output of your script
```
Using locale en_US
DaVinci Resolve checker 2.6.2
Installed DaVinci Resolve package: davinci-resolve 17.4.6-2
Chassis type: notebook
Installed OpenCL drivers: intel-compute-runtime opencl-mesa
Presented GPUs:
        TigerLake-LP GT2 [Iris Xe Graphics] (kernel driver in use: i915)
OpenGL vendor string: Intel

You should uninstall opencl-mesa. Otherwise DR (v17.1.1) behaves wrong: image is corrupted. But if you uncheck gpu checkbox in settings and relaunch DR, then even entire desktop session becomes corrupted and you only can reboot your pc. This is observed at least on amd gpu.
```

**Comment by melvyn2** [comment]
Also, the mesa OpenGL implementation itself works if you install a compatible driver like `rocm-opencl-runtime`. I have that driver stack installed and in use on my RX 580.

**Comment by Ashark** [comment]
@senge-studio How can you run DR on intel-only gpu? DR requires OpenCL to work, and it fails to work with DR, see https://wiki.archlinux.org/title/DaVinci_Resolve. If you have any additional information, please share.
