### ISSUE TITLE
cannot find pylspci (pypi and Arch Linux AUR)

### ISSUE THREAD

**Issue by Torxed** [Ashark/davinci-resolve-checker#32]
Followed these exact steps:
* Clone this repository.
* Install required dependencies:
  `sudo pacman -S expac mesa-demos python-distro`
* Install other required dependencies from aur (assuming you use yay):
  `yay -S python-pylspci`

And the `python-pylspci` package does not expose the `pylspci` package, whereas `pip install pylspci` does, but the script in this repo does not look for that package, it explicitly looks for `python-pylspci` through pacman hooks. A bit confusing.

And deleting the package is near impossible.
Because it's missing a bunch of information in the PKGBUILD. Such as:
```
provides=(python-pylspci)
conflicts=(python-pylspci)
replaces=(python-pylspci)
```

This isn't really advisable either:
```
md5sums=('SKIP')
```

I would propose: https://github.com/Ashark/davinci-resolve-checker/blob/2880b81f0c745e3de078266b4952e76568ebbc92/davinci-resolve-checker.py#L28

Got changed to something like (And I'll stick with pseudo bash here):
```bash
$ python -c "import pylspci"
$ if [ $? -ne 0 ]; echo "Missing package pylspci" && exit $?
```

The reason why you probably got it working in #11 is because after a few back and fourths of installing/removing, once you've `yay -S python-pylspci` and then done `pip install pylspci` it will correctly identify itself to Python as `lspci`. But it's a bit of madness to rely on this package.

Side note, this script will tell users to:
> You should uninstall opencl-mesa. Otherwise DR (v17.1.1) behaves wrong: image is corrupted.

But when doing:
```
$ sudo pacman -Rs opencl-mesa
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing opencl-mesa breaks dependency 'opencl-driver' required by davinci-resolve
```

Which contradicts.. No idea if that's intended, but I'll save myself a second issue creation by casually dropping it off at the end.
Any feedback would be welcome.

**Comment by Ashark** [comment]
> md5sums=('SKIP')

I wrote maintainer to fix that.

In 2.7.2 I check for the modules, so you can install via pip.

> removing opencl-mesa breaks dependency 'opencl-driver' required by davinci-resolve

DR package wants at least one opencl-driver providing package. To force uninstall (if you know you will satisfy dependency by another package later), use `pacman -Rdd opencl-mesa`.
