### ISSUE TITLE
Check for amd gpu generation (for determining if progl is needed)

### ISSUE THREAD

**Issue by Ashark** [Ashark/davinci-resolve-checker#33]
I need to find out if there is a way to check amd gpu generation.

In the Vega and onward gpus it is possible to not require progl. Unfortunately, not for older gpus currently, see https://gitlab.freedesktop.org/mesa/mesa/-/issues/6256.

**Comment by Ashark** [comment]
I currently solved it by checking if device name contains substring of the codename. See https://stackoverflow.com/a/72927956/7869636

**Comment by Axolord** [comment]
I have a Ryzen 3500U with "Radeon Vega Mobile Gfx". So from reading the arch wiki, it should work without libgl and the pro driver, but the script says:
```
Using locale en_US
DaVinci Resolve checker 3.0.0
Installed DaVinci Resolve package: 
Chassis type: notebook
Installed OpenCL drivers: 
Presented GPUs:
	Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (kernel driver in use: amdgpu)
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Vega 8 Graphics (raven, LLVM 14.0.6, DRM 3.42, 5.15.78-1-MANJARO)

Warning: not found your gpu in list of codenames. Assuming it is old gpu requiring progl. If that is untrue, please report.
You are not using Pro OpenGL implementation. Install amdgpu-pro-libgl and run DaVinci Resolve with progl prefix. Otherwise it will crash.
```

is this how it is supposed to be? Or does your script falsely not match vega mobile?

**Comment by Ashark** [comment]
Try to manually edit the Vega name, see https://github.com/Ashark/davinci-resolve-checker/pull/36/files
