### ISSUE TITLE
Reporting unknown chassis type

### ISSUE THREAD

**Issue by robwithhair** [Ashark/davinci-resolve-checker#39]
```
[robwithhair@workstation-1 davinci-resolve-checker]$ ./davinci-resolve-checker.py 
Locale unavailable: en_GB, using en_US instead
Using locale en_US
DaVinci Resolve checker 5.0.0
Installed DaVinci Resolve package: 
Chassis type: Tower
Warning: you chassis type is not supported by the script. Please report your case.
```

Hope this helps

**Comment by Ashark** [comment]
What is your hardware model? I guess it is should be a desktop, not a laptop?

**Comment by grace-the-nerd** [comment]
Received the same message.

✦5  ╰─λ ./davinci-resolve-checker.py
Using locale en_US
DaVinci Resolve checker 5.2.5
Installed DaVinci Resolve package:
Chassis type: Other
Warning: you chassis type is not supported by the script. Please report your case.

**Comment by Ashark** [comment]
It is not the same, yours is "Other".

**Comment by madranet** [comment]
Same... or, if you're a pedant "Similar"...


```
python ~/Downloads/davinci-resolve-checker/davinci-resolve-checker.py 
Locale unavailable: en_GB, using en_US instead
Using locale en_US
DaVinci Resolve checker 5.2.5
Installed DaVinci Resolve package: 
Chassis type: All in One
Warning: you chassis type is not supported by the script. Please report your case
```

**Comment by madranet** [comment]
I guessed that's what that line was actually doimg. 

The confusion [for me anyway] was that the script seems to bale out after identifying the chassis type as "not supported".  Yet, as we've seen from posters here, our chassis types have been variably identified as "Tower", "Other" and "All in One". which begs the question "Which chassis types ARE supported?" I looked over the Readme again to see if I'd missed the fact that this script is only intended for laptops [the only other "chassis type" I can think of]. But there's nothing to this effect. Hence the confusion.

FWIW: 

Just for the fun of it, I was trying to get DaVinci Resolve to launch on an ancient iMac running Arch and with a creaky old Nvidia GeForce graphics card. I was pretty sure it wouldn't work, or would run like a dog if it even launched. But I got bored of chasing one error after another so followed a link from the Resolve site to try this script and see if it would give me a more comprehensive run-down on what needed to be installed or upgraded.

I realise I'm probably not the target audience for this script.  As I say it was only a bit of idle fun. But I still think the error is confusing.  If the script can only run on laptops,  maybe make this clear in the rReadme or the error message.

**Comment by Ashark** [comment]
The script is intended to run on both laptops and desktops.

**Comment by madranet** [comment]
Aren't "Tower" and "All in One" also "Desktops" --assuming the definition is basically "Not a laptop"?  I've  just had a quick look at the script and it  rejects anything not a laptop and not defining itself as a "Desktop" which seems a bit restrictive . After all, an "All in One" and a "Tower" are also desktops. 


```python
print(local_str["chassis"], local_str.get(chassis_type, chassis_type))
supported_mobile_chassis_types = ["Laptop", "Notebook", "Space-saving", "Convertible", "Portable"]
if chassis_type != "Desktop" and chassis_type not in supported_mobile_chassis_types:
    print(local_str["unsupported chassis"])
    exit(1)
```

**Comment by grace-the-nerd** [comment]
I have a desktop running Proxmox and gpu is a RX 6600. Seeing as my machine is VM, more than likely why this script does not work. I got Resolve up and running anyway though.

**Comment by Ashark** [comment]
@grace-the-nerd Thanks. Added it as well.
