### ISSUE TITLE
Please add cachyos and Phoenix to list of distros/ gpus

### ISSUE THREAD

**Issue by sgmihai** [Ashark/davinci-resolve-checker#44]
after adding "cachyos" on line 33: if distro.id() not in {"arch", "manjaro", "endeavouros", "garuda", "cachyos"}:
(please add it, it's a great distro):

Using locale en_US
DaVinci Resolve checker 5.2.7
Installed DaVinci Resolve package: 
Chassis type: notebook
Installed OpenCL drivers:
        lib32-opencl-clover-mesa 1:23.3.5-1
        lib32-opencl-rusticl-mesa 1:23.3.5-1
        opencl-clover-mesa 1:23.3.5-2
        opencl-rusticl-mesa 1:23.3.5-2
        rocm-opencl-runtime 5.7.1-1.1
Presented GPUs:
        Phoenix1 (kernel driver in use: amdgpu)
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 16.0.6, DRM 3.57, 6.8.0-rc3-1-cachyos-rc-lto)
clinfo detected platforms and devices:
        rusticl (number of devices: 0)
        Clover (number of devices: 1)
                AMD Radeon Graphics (radeonsi, gfx1103_r1, LLVM 16.0.6, DRM 3.57, 6.8.0-rc3-1-cachyos-rc-lto)
        AMD Accelerated Parallel Processing (roc) (number of devices: 1)
                AMD Radeon Graphics

Warning: not found your gpu in list of codenames. Assuming it is old gpu requiring progl. If that is untrue, please report.
You should use ROC_ENABLE_PRE_VEGA=1 environment variable. Otherwise use pro stack (run checker with --pro), because legacy opencl requires progl to work.

If I run with "ROC_ENABLE_PRE_VEGA=1", I get "All seems good. You should be able to run DaVinci Resolve successfully."

Getting crashes on resolve studio, don't have to do much, "the gpu failed to perform image processing because of an error. Error code -1" and "'/opt/resolve/bin/resolve' terminated by signal SIGSEGV (Address boundary error)"

No idea what I need or missing, or if this gpu (phoenix igpu) is even supported.

**Comment by Ashark** [comment]
Done.
> No idea what I need or missing, or if this gpu (phoenix igpu) is even supported.

Sorry, I have no idea either. I have not got such hardware. If you find that out, you can then add this info so I add it to script.
