### ISSUE TITLE
AMD APU laptop works with DC Ryzen 7 4800u and Vega 8

### ISSUE THREAD

**Issue by arbobendik** [Ashark/davinci-resolve-checker#5]
I tried to run DC with opencl-amd, opencl-mesa / amdgpu-pro-libgl .The script showed me :" I did not found a working configuration with AMD gpu on laptop yet. Did you?". Then I uninstalled opencl-mesa and DC worked. So for other AMD APU owners you could help them by checking if it's an APU and tell them to uninstall the opencl-mesa driver which comes preinstalled with most distros. Thanks in advance.

**Comment by Ashark** [comment]
> I tried to run DC

What is DC? You mean DR (davinci resolve)?
Do you actually run DR with your integrated GPU? Can you then run a newer 1.3.1 version, it will show your configuration.

**Comment by Ashark** [comment]
@arbobendik I would like to test it and print a help message to remove opencl-mesa when/if needed. But unfortunately, I do not have a working configuration with amdgpu for now. If you have it, please share output of the davinci-resolve-checker.
