### ISSUE TITLE
Chassis type: Mini PC

### ISSUE THREAD

**Issue by alterogi** [Ashark/davinci-resolve-checker#53]
Hi there.
Steps to reproduce:

> ❯ ./davinci-resolve-checker.py 
> Using locale en_US
> DaVinci Resolve checker 5.2.8
> Installed DaVinci Resolve package: 
> Chassis type: Mini PC
> Warning: you chassis type is not supported by the script. Please report your case.

**Comment by Ashark** [comment]
It is a small desktop PC, right?

**Comment by alterogi** [comment]
Yeah, one of these Chinese cheapo machines: https://www.bee-link.com/
