### ISSUE TITLE
T14s: I did not found a working configuration with AMD gpu on laptop yet. Did you?

### ISSUE THREAD

**Issue by kaihendry** [Ashark/davinci-resolve-checker#6]
Similar to https://github.com/Ashark/davinci-resolve-checker/issues/5 but with a T14s

https://wiki.archlinux.org/index.php/Lenovo_Thinkpad_T14s_(AMD)_Gen_1

```
[hendry@t14s davinci-resolve-checker]$ python davinci-resolve-checker.py
DaVinci Resolve checker 1.3.1
Your configuration:
Chassis: laptop
Installed OpenCL drivers: opencl-mesa
Presented GPUs:
        Renoir driver: amdgpu
OpenGL vendor string: X.Org
I did not found a working configuration with AMD gpu on laptop yet. Did you?
```

davinci-resolve 16.2.5-1 fails with Failed to initialize OpenCL boards

**Comment by trillerpfeife** [comment]
I got Resolve running on ThinkPad E15 2. Gen (AMD) using the following Workaround:
[https://wiki.archlinux.org/index.php/AMDGPU_PRO#Workaround_for_using_proprietary_OpenGL](https://wiki.archlinux.org/index.php/AMDGPU_PRO#Workaround_for_using_proprietary_OpenGL)

**Comment by Ashark** [comment]
@trillerpfeife are you using dgpu or igpu? Could you provide output of the script?

**Comment by trillerpfeife** [comment]
IGPU, which script?

**Comment by Ashark** [comment]
davinci-resolve-checker.py script. In version 1.3.1 I added output of the configuration.

**Comment by trillerpfeife** [comment]
;) shure
```
[flux@flux-20t9s00k00 davinci-resolve-checker]$ python davinci-resolve-checker.py 
DaVinci Resolve checker 1.3.1
Your configuration:
Chassis: laptop
Installed OpenCL drivers: opencl-amdgpu-pro-pal
Presented GPUs:
	Renoir driver: amdgpu
OpenGL vendor string: Advanced Micro Devices, Inc.
I did not found a working configuration with AMD gpu on laptop yet. Did you?
```

**Comment by trillerpfeife** [comment]
In order to use the Resolve i have to install `opencl-amdgpu-pro-pal` and remove it after using.

**Comment by Ashark** [comment]
You mean amdgpu-pro-libgl I think.

**Comment by trillerpfeife** [comment]
Yes you right!

**Comment by Ashark** [comment]
I will experiment with detecting primary GPU to differentiate with I+A laptops. I have found this question https://stackoverflow.com/questions/19985131/how-identify-the-primary-video-card-on-linux-programmatically

**Comment by Ashark** [comment]
@trillerpfeife Can you still run DR? I could make an ok message for amd igpu only laptop, but I have lost a point when I could launch dr correcly. Could you please test it with latest driver (20.45_1188099)  and show output of the davinci-resolve-checker?

**Comment by Ashark** [comment]
@trillerpfeife By the way, you can also test with opencl-amd and fill in the result here: https://wiki.archlinux.org/index.php/DaVinci_Resolve, because there is no longer opencl-amdgpu-pro-pal

**Comment by nigo81** [comment]
> I got Resolve running on ThinkPad E15 2. Gen (AMD) using the following Workaround:
> https://wiki.archlinux.org/index.php/AMDGPU_PRO#Workaround_for_using_proprietary_OpenGL
```
yay -S amdgpu-pro-libgl
```
after `yay` to install `amdgpu-pro-libgl`, run `sudo progl /opt/resolve/bin/resolve`,then davinci resolve will start successfully.
thanks a lot.

**Comment by kaihendry** [comment]
Cool, I can also start davince-resolve 17.0-1 on my T14s on Arch. But it doesn't seem to be able to grok MP4 files from Sony camera. :man_facepalming: 

```
(ins)[hendry@t14s CLIP]$ ffprobe C0517.MP4 2>&1 | grep Stream
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709/bt709/iec61966-2-4), 3840x2160 [SAR 1:1 DAR 16:9], 57159 kb/s, 29.97 fps, 29.97 tbr, 30k tbn, 59.94 tbc (default)
    Stream #0:1(und): Audio: pcm_s16be (twos / 0x736F7774), 48000 Hz, 2 channels, s16, 1536 kb/s (default)
    Stream #0:2(und): Data: none (rtmd / 0x646D7472), 1227 kb/s (default)
```
