### ISSUE TITLE
ModuleNotFoundError: No module named 'distro'

### ISSUE THREAD

**Issue by gagangulyani** [Ashark/davinci-resolve-checker#9]
I'm getting this error message while trying to run the python script.

**Comment by gagangulyani** [comment]
Solution is

`pip install distro`

Though, it would be great if it was mentioned in the README.md to install it prior to running the script.

**Comment by eriteric** [comment]
I have it installed and I still get this message. Any idea why?

**Comment by Ashark** [comment]
Check that you are running in the desired environment. 
You probably installed package in virtual environment, but running in system environment.

**Comment by sdg363** [comment]
getting the same error, except distro is installed system wide (with `sudo pacman -S python-distro`)
any help?

**Comment by Ashark** [comment]
❯ yay -Q python-distro
python-distro 1.9.0-3

This is version installed on my system, and seems it works for me.
